services:
  server:
    build: ./
    ports:
       - 8080:8080
    depends_on:
       - postgres  # Ensure the database starts before the app
    environment:
       POSTGRES_HOST: postgres # Uses the service name of the database as the host
       POSTGRES_PORT: 5432
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres 
       POSTGRES_DB: postgres

  postgres:
    image: postgres:16-alpine # Swap this with the image for your org
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres 
       POSTGRES_DB: postgres